# Generated by Django 4.2.1 on 2023-05-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='direction',
            field=models.IntegerField(default=2),
        ),
    ]
