# Generated by Django 4.2.1 on 2023-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slot',
        ),
        migrations.AddField(
            model_name='item',
            name='game_id',
            field=models.IntegerField(choices=[(1, 'Knife'), (2, 'Wooden Shield')], default=0),
        ),
    ]
