# Generated by Django 4.2.1 on 2023-06-03 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_remove_item_name_remove_item_slot_item_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='bag_0',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag_0', to='characters.item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='bag_1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag_1', to='characters.item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='bag_2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag_2', to='characters.item'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='bag_3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bag_3', to='characters.item'),
        ),
    ]
