# Generated by Django 4.2.1 on 2023-06-11 19:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patch_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchnote',
            name='author',
        ),
        migrations.AlterField(
            model_name='patchnote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patch_notes/static/img/'),
        ),
        migrations.AddField(
            model_name='patchnote',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
