# Generated by Django 4.2.1 on 2023-06-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_notes', '0003_remove_patchnote_author_patchnote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnote',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
