# Generated by Django 4.2.1 on 2023-06-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_notes', '0004_patchnote_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnote',
            name='visible',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
