# Generated by Django 4.2.1 on 2023-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_notes', '0005_alter_patchnote_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnote',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
