# Generated by Django 4.2.1 on 2023-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patch_notes', '0007_alter_patchnote_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
